export const API_URL="http://localhost:5000"

export const STORE_LOGGED_IN_USER_DETAILS="STORE_LOGGED_IN_USER_DETAILS";

export const SELECTED_MATCH_DETAILS="SELECTED_MATCH_DETAILS";

export const EDIT_TODO_INFO="EDIT_TODO_INFO";

export const SHOW_SIGN_IN_OR_SIGN_UP="SHOW_SIGN_IN_OR_SIGN_UP";

export const ACCESS_TOKEN="ACCESS_TOKEN";

export const SELECTED_USER_PROFILE_ID="SELECTED_USER_PROFILE_ID";